# Generated by Django 4.1.7 on 2023-02-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', '-creation_time']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
